trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm test
      cat coverage/lcov.info | npx coveralls
    displayName: 'Run Tests'
    env:
      SERVICE_ACCOUNT_KEY_BASE64: $(SERVICE_ACCOUNT_KEY_BASE64)
      COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
