trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm test
    displayName: 'npm install and test'
    env:
      SERVICE_ACCOUNT_KEY_BASE64: $(SERVICE_ACCOUNT_KEY_BASE64)

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverage/cobertura-coverage.xml
      reportDirectory: coverage/
