name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run Tests
        run: |
          set -e
          node -v
          npm -v
          java --version
          npm install
          npm test
      - name: Post Coverage
        uses: codecov/codecov-action@v2
