name: Build & Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build & Run Tests
        run: |
          set -e
          node -v
          npm -v
          java --version
          npm install
          npm test
      - name: Release Dry Run
        run: npx standard-version --dry-run
      - name: Post Coverage
        uses: codecov/codecov-action@v2
